apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-db-pvc
  namespace: devconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-db
  namespace: devconnect
  labels:
    app: project-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-db
  template:
    metadata:
      labels:
        app: project-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: project_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: project-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: project-db-storage
          persistentVolumeClaim:
            claimName: project-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: project-db
  namespace: devconnect
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: project-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-db-pvc
  namespace: devconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-db
  namespace: devconnect
  labels:
    app: event-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-db
  template:
    metadata:
      labels:
        app: event-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: event_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: event-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: event-db-storage
          persistentVolumeClaim:
            claimName: event-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: event-db
  namespace: devconnect
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: event-db
