apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
  namespace: techhub
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/usersdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_REDIS_HOST: "redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SERVER_PORT: "8080"