apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: devconnect
  labels:
    app: project-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: project-service
  type: ClusterIP
