apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
  namespace: techhub
data:
  DB_HOST: "event-db"
  DB_PORT: "5432"
  DB_NAME: "event_db"
  DB_USERNAME: "postgres"
  REDIS_HOST: "event-redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "event-kafka:9092"
