apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # allow ArgoCD to sync from public GitHub repos
  repositories: |
    - url: https://github.com/ENSIAS-MEH/development-platform-geeks_team.git