JWT_SECRET = 44kZGaySDVJ87wlmYZnOqJKQmrQNYT1fZdJZNfCQV0caGrZFK6fFQh7MRkoJQ+F9FnZh2XfaACfV8hieLkrQBg==
#GITHUB
CLIENT_ID = Ov23liOgHR7PTIKeUxMr
CLIENT_SECRET = 5c97c5d62a5de1c65158bf5b4590dfa18d5dec2c

#GOOGLE
GOOGLE_CLIENT_ID = 830884241079-soo9stan3j8dd9g6mbl6c9qdao075j30.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET = 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